php5:
  build: app/
  ports:
    - "8002:8002"
  volumes:
    - backend/admin/view:/vapescape/admin/view
    - backend/catalog/view:/vapescape/catalog/view
    - configs/ngx-production:/etc/nginx/sites-available/default
    - configs/nginx.conf:/etc/nginx/nginx.conf
  environment:
    DB_HOST: "vapescape.com.au"
    DB_PASS: "vapescape"
    HTTP_SERVER: "http://vapescape.com.au/"
    HTTPS_SERVER: "http://vapescape.com.au/"