php5:
  build: app/
  ports:
    - "8002:8002"
  volumes:
    - configs/ngx-production:/etc/nginx/sites-available/default
    - configs/nginx.conf:/etc/nginx/nginx.conf
  environment:
    MYSQL_PORT_3306_TCP_ADDR: vapescape.com.au
    MYSQL_VAPE_USERNAME: vape
    MYSQL_VAPE_PASSWORD: vapescape
    MYSQL_VAPE_DATABASE: vapescape
    MYSQL_VAPE_DATABASE_PREFIX: oc_
    HTTP_SERVER: http://vapescape.com.au/
    HTTPS_SERVER: http://vapescape.com.au/
    HTTP_ADMIN_SERVER: http://vapescape.com.au/admin/
    HTTPS_ADMIN_SERVER: http://vapescape.com.au/admin/