php5:
  build: app/
  ports:
    - "8002:8002"
  volumes:
    - configs/ngx-production:/etc/nginx/sites-available/default
    - configs/nginx.conf:/etc/nginx/nginx.conf
    - configs/fpm-config:/etc/php5/fpm/pool.d/vape.conf